const elements = [
  {
    num: 1,
    symbol: "H",
    name: "Сутегі",
    mass: 1.008,
    category: "nonmetal",
    electronConfig: "1s¹",
    meltingPoint: -259.16,
    boilingPoint: -252.87,
    density: 0.00008988,
    group: 1,
    period: 1,
  },
  {
    num: 2,
    symbol: "He",
    name: "Гелий",
    mass: 4.003,
    category: "noble",
    electronConfig: "1s²",
    meltingPoint: -272.2,
    boilingPoint: -268.93,
    density: 0.0001785,
    group: 18,
    period: 1,
  },
  {
    num: 3,
    symbol: "Li",
    name: "Литий",
    mass: 6.941,
    category: "alkali",
    electronConfig: "[He] 2s¹",
    meltingPoint: 180.5,
    boilingPoint: 1342,
    density: 0.534,
    group: 1,
    period: 2,
  },
  {
    num: 4,
    symbol: "Be",
    name: "Бериллий",
    mass: 9.012,
    category: "alkaline",
    electronConfig: "[He] 2s²",
    meltingPoint: 1287,
    boilingPoint: 2470,
    density: 1.85,
    group: 2,
    period: 2,
  },
  {
    num: 5,
    symbol: "B",
    name: "Бор",
    mass: 10.81,
    category: "metalloid",
    electronConfig: "[He] 2s² 2p¹",
    meltingPoint: 2075,
    boilingPoint: 4000,
    density: 2.34,
    group: 13,
    period: 2,
  },
  {
    num: 6,
    symbol: "C",
    name: "Көміртегі",
    mass: 12.01,
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p²",
    meltingPoint: 3550,
    boilingPoint: 4027,
    density: 2.267,
    group: 14,
    period: 2,
  },
  {
    num: 7,
    symbol: "N",
    name: "Азот",
    mass: 14.01,
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p³",
    meltingPoint: -210,
    boilingPoint: -195.8,
    density: 0.0012506,
    group: 15,
    period: 2,
  },
  {
    num: 8,
    symbol: "O",
    name: "Оттегі",
    mass: 16.0,
    category: "nonmetal",
    electronConfig: "[He] 2s² 2p⁴",
    meltingPoint: -218.3,
    boilingPoint: -182.9,
    density: 0.001429,
    group: 16,
    period: 2,
  },
  {
    num: 9,
    symbol: "F",
    name: "Фтор",
    mass: 19.0,
    category: "halogen",
    electronConfig: "[He] 2s² 2p⁵",
    meltingPoint: -219.6,
    boilingPoint: -188.1,
    density: 0.001696,
    group: 17,
    period: 2,
  },
  {
    num: 10,
    symbol: "Ne",
    name: "Неон",
    mass: 20.18,
    category: "noble",
    electronConfig: "[He] 2s² 2p⁶",
    meltingPoint: -248.6,
    boilingPoint: -246.1,
    density: 0.0008999,
    group: 18,
    period: 2,
  },
  {
    num: 11,
    symbol: "Na",
    name: "Натрий",
    mass: 22.99,
    category: "alkali",
    electronConfig: "[Ne] 3s¹",
    meltingPoint: 97.72,
    boilingPoint: 883,
    density: 0.971,
    group: 1,
    period: 3,
  },
  {
    num: 12,
    symbol: "Mg",
    name: "Магний",
    mass: 24.31,
    category: "alkaline",
    electronConfig: "[Ne] 3s²",
    meltingPoint: 650,
    boilingPoint: 1090,
    density: 1.738,
    group: 2,
    period: 3,
  },
  {
    num: 13,
    symbol: "Al",
    name: "Алюминий",
    mass: 26.98,
    category: "post-transition",
    electronConfig: "[Ne] 3s² 3p¹",
    meltingPoint: 660.3,
    boilingPoint: 2519,
    density: 2.698,
    group: 13,
    period: 3,
  },
  {
    num: 14,
    symbol: "Si",
    name: "Кремний",
    mass: 28.09,
    category: "metalloid",
    electronConfig: "[Ne] 3s² 3p²",
    meltingPoint: 1414,
    boilingPoint: 3265,
    density: 2.3296,
    group: 14,
    period: 3,
  },
  {
    num: 15,
    symbol: "P",
    name: "Фосфор",
    mass: 30.97,
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p³",
    meltingPoint: 44.15,
    boilingPoint: 280.5,
    density: 1.82,
    group: 15,
    period: 3,
  },
  {
    num: 16,
    symbol: "S",
    name: "Күкірт",
    mass: 32.07,
    category: "nonmetal",
    electronConfig: "[Ne] 3s² 3p⁴",
    meltingPoint: 115.2,
    boilingPoint: 444.6,
    density: 2.067,
    group: 16,
    period: 3,
  },
  {
    num: 17,
    symbol: "Cl",
    name: "Хлор",
    mass: 35.45,
    category: "halogen",
    electronConfig: "[Ne] 3s² 3p⁵",
    meltingPoint: -101.5,
    boilingPoint: -34.04,
    density: 0.003214,
    group: 17,
    period: 3,
  },
  {
    num: 18,
    symbol: "Ar",
    name: "Аргон",
    mass: 39.95,
    category: "noble",
    electronConfig: "[Ne] 3s² 3p⁶",
    meltingPoint: -189.3,
    boilingPoint: -185.8,
    density: 0.001784,
    group: 18,
    period: 3,
  },
  {
    num: 19,
    symbol: "K",
    name: "Калий",
    mass: 39.1,
    category: "alkali",
    electronConfig: "[Ar] 4s¹",
    meltingPoint: 63.5,
    boilingPoint: 759,
    density: 0.862,
    group: 1,
    period: 4,
  },
  {
    num: 20,
    symbol: "Ca",
    name: "Кальций",
    mass: 40.08,
    category: "alkaline",
    electronConfig: "[Ar] 4s²",
    meltingPoint: 842,
    boilingPoint: 1484,
    density: 1.54,
    group: 2,
    period: 4,
  },
  {
    num: 21,
    symbol: "Sc",
    name: "Скандий",
    mass: 44.96,
    category: "transition",
    electronConfig: "[Ar] 3d¹ 4s²",
    meltingPoint: 1541,
    boilingPoint: 2836,
    density: 2.989,
    group: 3,
    period: 4,
  },
  {
    num: 22,
    symbol: "Ti",
    name: "Титан",
    mass: 47.87,
    category: "transition",
    electronConfig: "[Ar] 3d² 4s²",
    meltingPoint: 1668,
    boilingPoint: 3287,
    density: 4.54,
    group: 4,
    period: 4,
  },
  {
    num: 23,
    symbol: "V",
    name: "Ванадий",
    mass: 50.94,
    category: "transition",
    electronConfig: "[Ar] 3d³ 4s²",
    meltingPoint: 1910,
    boilingPoint: 3407,
    density: 6.11,
    group: 5,
    period: 4,
  },
  {
    num: 24,
    symbol: "Cr",
    name: "Хром",
    mass: 52.0,
    category: "transition",
    electronConfig: "[Ar] 3d⁵ 4s¹",
    meltingPoint: 1907,
    boilingPoint: 2671,
    density: 7.15,
    group: 6,
    period: 4,
  },
  {
    num: 25,
    symbol: "Mn",
    name: "Марганец",
    mass: 54.94,
    category: "transition",
    electronConfig: "[Ar] 3d⁵ 4s²",
    meltingPoint: 1246,
    boilingPoint: 2061,
    density: 7.44,
    group: 7,
    period: 4,
  },
  {
    num: 26,
    symbol: "Fe",
    name: "Темір",
    mass: 55.85,
    category: "transition",
    electronConfig: "[Ar] 3d⁶ 4s²",
    meltingPoint: 1538,
    boilingPoint: 2861,
    density: 7.874,
    group: 8,
    period: 4,
  },
  {
    num: 27,
    symbol: "Co",
    name: "Кобальт",
    mass: 58.93,
    category: "transition",
    electronConfig: "[Ar] 3d⁷ 4s²",
    meltingPoint: 1495,
    boilingPoint: 2927,
    density: 8.86,
    group: 9,
    period: 4,
  },
  {
    num: 28,
    symbol: "Ni",
    name: "Никель",
    mass: 58.69,
    category: "transition",
    electronConfig: "[Ar] 3d⁸ 4s²",
    meltingPoint: 1455,
    boilingPoint: 2913,
    density: 8.912,
    group: 10,
    period: 4,
  },
  {
    num: 29,
    symbol: "Cu",
    name: "Мыс",
    mass: 63.55,
    category: "transition",
    electronConfig: "[Ar] 3d¹⁰ 4s¹",
    meltingPoint: 1084.6,
    boilingPoint: 2562,
    density: 8.96,
    group: 11,
    period: 4,
  },
  {
    num: 30,
    symbol: "Zn",
    name: "Мырыш",
    mass: 65.38,
    category: "transition",
    electronConfig: "[Ar] 3d¹⁰ 4s²",
    meltingPoint: 419.5,
    boilingPoint: 907,
    density: 7.134,
    group: 12,
    period: 4,
  },
  {
    num: 31,
    symbol: "Ga",
    name: "Галлий",
    mass: 69.72,
    category: "post-transition",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p¹",
    meltingPoint: 29.76,
    boilingPoint: 2204,
    density: 5.907,
    group: 13,
    period: 4,
  },
  {
    num: 32,
    symbol: "Ge",
    name: "Германий",
    mass: 72.63,
    category: "metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p²",
    meltingPoint: 938.3,
    boilingPoint: 2833,
    density: 5.323,
    group: 14,
    period: 4,
  },
  {
    num: 33,
    symbol: "As",
    name: "Мышьяк",
    mass: 74.92,
    category: "metalloid",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p³",
    meltingPoint: 817,
    boilingPoint: 614,
    density: 5.776,
    group: 15,
    period: 4,
  },
  {
    num: 34,
    symbol: "Se",
    name: "Селен",
    mass: 78.96,
    category: "nonmetal",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁴",
    meltingPoint: 221,
    boilingPoint: 685,
    density: 4.809,
    group: 16,
    period: 4,
  },
  {
    num: 35,
    symbol: "Br",
    name: "Бром",
    mass: 79.9,
    category: "halogen",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁵",
    meltingPoint: -7.2,
    boilingPoint: 58.8,
    density: 3.122,
    group: 17,
    period: 4,
  },
  {
    num: 36,
    symbol: "Kr",
    name: "Криптон",
    mass: 83.8,
    category: "noble",
    electronConfig: "[Ar] 3d¹⁰ 4s² 4p⁶",
    meltingPoint: -157.4,
    boilingPoint: -153.2,
    density: 0.003733,
    group: 18,
    period: 4,
  },
  {
    num: 37,
    symbol: "Rb",
    name: "Рубидий",
    mass: 85.47,
    category: "alkali",
    electronConfig: "[Kr] 5s¹",
    meltingPoint: 39.3,
    boilingPoint: 688,
    density: 1.532,
    group: 1,
    period: 5,
  },
  {
    num: 38,
    symbol: "Sr",
    name: "Стронций",
    mass: 87.62,
    category: "alkaline",
    electronConfig: "[Kr] 5s²",
    meltingPoint: 777,
    boilingPoint: 1382,
    density: 2.64,
    group: 2,
    period: 5,
  },
  {
    num: 39,
    symbol: "Y",
    name: "Иттрий",
    mass: 88.91,
    category: "transition",
    electronConfig: "[Kr] 4d¹ 5s²",
    meltingPoint: 1526,
    boilingPoint: 3345,
    density: 4.469,
    group: 3,
    period: 5,
  },
  {
    num: 40,
    symbol: "Zr",
    name: "Цирконий",
    mass: 91.22,
    category: "transition",
    electronConfig: "[Kr] 4d² 5s²",
    meltingPoint: 1855,
    boilingPoint: 4409,
    density: 6.506,
    group: 4,
    period: 5,
  },
  {
    num: 41,
    symbol: "Nb",
    name: "Ниобий",
    mass: 92.91,
    category: "transition",
    electronConfig: "[Kr] 4d⁴ 5s¹",
    meltingPoint: 2477,
    boilingPoint: 4744,
    density: 8.57,
    group: 5,
    period: 5,
  },
  {
    num: 42,
    symbol: "Mo",
    name: "Молибден",
    mass: 95.95,
    category: "transition",
    electronConfig: "[Kr] 4d⁵ 5s¹",
    meltingPoint: 2623,
    boilingPoint: 4639,
    density: 10.22,
    group: 6,
    period: 5,
  },
  {
    num: 43,
    symbol: "Tc",
    name: "Технеций",
    mass: 98,
    category: "transition",
    electronConfig: "[Kr] 4d⁵ 5s²",
    meltingPoint: 2157,
    boilingPoint: 4265,
    density: 11.5,
    group: 7,
    period: 5,
  },
  {
    num: 44,
    symbol: "Ru",
    name: "Рутений",
    mass: 101.07,
    category: "transition",
    electronConfig: "[Kr] 4d⁷ 5s¹",
    meltingPoint: 2334,
    boilingPoint: 4150,
    density: 12.37,
    group: 8,
    period: 5,
  },
  {
    num: 45,
    symbol: "Rh",
    name: "Родий",
    mass: 102.91,
    category: "transition",
    electronConfig: "[Kr] 4d⁸ 5s¹",
    meltingPoint: 1964,
    boilingPoint: 3695,
    density: 12.41,
    group: 9,
    period: 5,
  },
  {
    num: 46,
    symbol: "Pd",
    name: "Палладий",
    mass: 106.42,
    category: "transition",
    electronConfig: "[Kr] 4d¹⁰",
    meltingPoint: 1554.9,
    boilingPoint: 2963,
    density: 12.02,
    group: 10,
    period: 5,
  },
  {
    num: 47,
    symbol: "Ag",
    name: "Күміс",
    mass: 107.87,
    category: "transition",
    electronConfig: "[Kr] 4d¹⁰ 5s¹",
    meltingPoint: 961.8,
    boilingPoint: 2162,
    density: 10.501,
    group: 11,
    period: 5,
  },
  {
    num: 48,
    symbol: "Cd",
    name: "Кадмий",
    mass: 112.41,
    category: "transition",
    electronConfig: "[Kr] 4d¹⁰ 5s²",
    meltingPoint: 321.1,
    boilingPoint: 767,
    density: 8.69,
    group: 12,
    period: 5,
  },
  {
    num: 49,
    symbol: "In",
    name: "Индий",
    mass: 114.82,
    category: "post-transition",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p¹",
    meltingPoint: 156.6,
    boilingPoint: 2072,
    density: 7.31,
    group: 13,
    period: 5,
  },
  {
    num: 50,
    symbol: "Sn",
    name: "Қалайы",
    mass: 118.71,
    category: "post-transition",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p²",
    meltingPoint: 231.9,
    boilingPoint: 2602,
    density: 7.287,
    group: 14,
    period: 5,
  },
  {
    num: 51,
    symbol: "Sb",
    name: "Сурьма",
    mass: 121.76,
    category: "metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p³",
    meltingPoint: 630.6,
    boilingPoint: 1587,
    density: 6.685,
    group: 15,
    period: 5,
  },
  {
    num: 52,
    symbol: "Te",
    name: "Теллур",
    mass: 127.6,
    category: "metalloid",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁴",
    meltingPoint: 449.5,
    boilingPoint: 988,
    density: 6.232,
    group: 16,
    period: 5,
  },
  {
    num: 53,
    symbol: "I",
    name: "Йод",
    mass: 126.9,
    category: "halogen",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁵",
    meltingPoint: 113.7,
    boilingPoint: 184.3,
    density: 4.93,
    group: 17,
    period: 5,
  },
  {
    num: 54,
    symbol: "Xe",
    name: "Ксенон",
    mass: 131.29,
    category: "noble",
    electronConfig: "[Kr] 4d¹⁰ 5s² 5p⁶",
    meltingPoint: -111.8,
    boilingPoint: -108.1,
    density: 0.005887,
    group: 18,
    period: 5,
  },
  {
    num: 55,
    symbol: "Cs",
    name: "Цезий",
    mass: 132.91,
    category: "alkali",
    electronConfig: "[Xe] 6s¹",
    meltingPoint: 28.44,
    boilingPoint: 671,
    density: 1.873,
    group: 1,
    period: 6,
  },
  {
    num: 56,
    symbol: "Ba",
    name: "Барий",
    mass: 137.33,
    category: "alkaline",
    electronConfig: "[Xe] 6s²",
    meltingPoint: 727,
    boilingPoint: 1897,
    density: 3.594,
    group: 2,
    period: 6,
  },
  {
    num: 57,
    symbol: "La",
    name: "Лантан",
    mass: 138.91,
    category: "lanthanide",
    electronConfig: "[Xe] 5d¹ 6s²",
    meltingPoint: 920,
    boilingPoint: 3464,
    density: 6.145,
    group: 3,
    period: 6,
  },
  {
    num: 58,
    symbol: "Ce",
    name: "Церий",
    mass: 140.12,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹ 5d¹ 6s²",
    meltingPoint: 795,
    boilingPoint: 3443,
    density: 6.77,
    group: null,
    period: 6,
  },
  {
    num: 59,
    symbol: "Pr",
    name: "Празеодим",
    mass: 140.91,
    category: "lanthanide",
    electronConfig: "[Xe] 4f³ 6s²",
    meltingPoint: 935,
    boilingPoint: 3520,
    density: 6.773,
    group: null,
    period: 6,
  },
  {
    num: 60,
    symbol: "Nd",
    name: "Неодим",
    mass: 144.24,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁴ 6s²",
    meltingPoint: 1024,
    boilingPoint: 3074,
    density: 7.007,
    group: null,
    period: 6,
  },
  {
    num: 61,
    symbol: "Pm",
    name: "Прометий",
    mass: 145,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁵ 6s²",
    meltingPoint: 1042,
    boilingPoint: 3000,
    density: 7.26,
    group: null,
    period: 6,
  },
  {
    num: 62,
    symbol: "Sm",
    name: "Самарий",
    mass: 150.36,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁶ 6s²",
    meltingPoint: 1072,
    boilingPoint: 1794,
    density: 7.52,
    group: null,
    period: 6,
  },
  {
    num: 63,
    symbol: "Eu",
    name: "Европий",
    mass: 151.96,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁷ 6s²",
    meltingPoint: 826,
    boilingPoint: 1529,
    density: 5.243,
    group: null,
    period: 6,
  },
  {
    num: 64,
    symbol: "Gd",
    name: "Гадолиний",
    mass: 157.25,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁷ 5d¹ 6s²",
    meltingPoint: 1312,
    boilingPoint: 3273,
    density: 7.895,
    group: null,
    period: 6,
  },
  {
    num: 65,
    symbol: "Tb",
    name: "Тербий",
    mass: 158.93,
    category: "lanthanide",
    electronConfig: "[Xe] 4f⁹ 6s²",
    meltingPoint: 1356,
    boilingPoint: 3230,
    density: 8.229,
    group: null,
    period: 6,
  },
  {
    num: 66,
    symbol: "Dy",
    name: "Диспрозий",
    mass: 162.5,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹⁰ 6s²",
    meltingPoint: 1407,
    boilingPoint: 2567,
    density: 8.55,
    group: null,
    period: 6,
  },
  {
    num: 67,
    symbol: "Ho",
    name: "Гольмий",
    mass: 164.93,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹¹ 6s²",
    meltingPoint: 1461,
    boilingPoint: 2720,
    density: 8.795,
    group: null,
    period: 6,
  },
  {
    num: 68,
    symbol: "Er",
    name: "Эрбий",
    mass: 167.26,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹² 6s²",
    meltingPoint: 1529,
    boilingPoint: 2868,
    density: 9.066,
    group: null,
    period: 6,
  },
  {
    num: 69,
    symbol: "Tm",
    name: "Тулий",
    mass: 168.93,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹³ 6s²",
    meltingPoint: 1545,
    boilingPoint: 1950,
    density: 9.321,
    group: null,
    period: 6,
  },
  {
    num: 70,
    symbol: "Yb",
    name: "Иттербий",
    mass: 173.05,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 6s²",
    meltingPoint: 819,
    boilingPoint: 1196,
    density: 6.965,
    group: null,
    period: 6,
  },
  {
    num: 71,
    symbol: "Lu",
    name: "Лютеций",
    mass: 174.97,
    category: "lanthanide",
    electronConfig: "[Xe] 4f¹⁴ 5d¹ 6s²",
    meltingPoint: 1652,
    boilingPoint: 3402,
    density: 9.84,
    group: 3,
    period: 6,
  },
  {
    num: 72,
    symbol: "Hf",
    name: "Гафний",
    mass: 178.49,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d² 6s²",
    meltingPoint: 2233,
    boilingPoint: 4603,
    density: 13.31,
    group: 4,
    period: 6,
  },
  {
    num: 73,
    symbol: "Ta",
    name: "Тантал",
    mass: 180.95,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d³ 6s²",
    meltingPoint: 3017,
    boilingPoint: 5458,
    density: 16.654,
    group: 5,
    period: 6,
  },
  {
    num: 74,
    symbol: "W",
    name: "Вольфрам",
    mass: 183.84,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d⁴ 6s²",
    meltingPoint: 3422,
    boilingPoint: 5555,
    density: 19.25,
    group: 6,
    period: 6,
  },
  {
    num: 75,
    symbol: "Re",
    name: "Рений",
    mass: 186.21,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d⁵ 6s²",
    meltingPoint: 3186,
    boilingPoint: 5596,
    density: 21.02,
    group: 7,
    period: 6,
  },
  {
    num: 76,
    symbol: "Os",
    name: "Осмий",
    mass: 190.23,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d⁶ 6s²",
    meltingPoint: 3033,
    boilingPoint: 5012,
    density: 22.61,
    group: 8,
    period: 6,
  },
  {
    num: 77,
    symbol: "Ir",
    name: "Иридий",
    mass: 192.22,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d⁷ 6s²",
    meltingPoint: 2446,
    boilingPoint: 4428,
    density: 22.56,
    group: 9,
    period: 6,
  },
  {
    num: 78,
    symbol: "Pt",
    name: "Платина",
    mass: 195.08,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d⁹ 6s¹",
    meltingPoint: 1768.3,
    boilingPoint: 3825,
    density: 21.46,
    group: 10,
    period: 6,
  },
  {
    num: 79,
    symbol: "Au",
    name: "Алтын",
    mass: 196.97,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",
    meltingPoint: 1064.2,
    boilingPoint: 2856,
    density: 19.282,
    group: 11,
    period: 6,
  },
  {
    num: 80,
    symbol: "Hg",
    name: "Сынап",
    mass: 200.59,
    category: "transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s²",
    meltingPoint: -38.83,
    boilingPoint: 356.7,
    density: 13.5336,
    group: 12,
    period: 6,
  },
  {
    num: 81,
    symbol: "Tl",
    name: "Таллий",
    mass: 204.38,
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",
    meltingPoint: 304,
    boilingPoint: 1473,
    density: 11.85,
    group: 13,
    period: 6,
  },
  {
    num: 82,
    symbol: "Pb",
    name: "Қорғасын",
    mass: 207.2,
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",
    meltingPoint: 327.5,
    boilingPoint: 1749,
    density: 11.342,
    group: 14,
    period: 6,
  },
  {
    num: 83,
    symbol: "Bi",
    name: "Висмут",
    mass: 208.98,
    category: "post-transition",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",
    meltingPoint: 271.5,
    boilingPoint: 1564,
    density: 9.807,
    group: 15,
    period: 6,
  },
  {
    num: 84,
    symbol: "Po",
    name: "Полоний",
    mass: 209,
    category: "metalloid",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",
    meltingPoint: 254,
    boilingPoint: 962,
    density: 9.32,
    group: 16,
    period: 6,
  },
  {
    num: 85,
    symbol: "At",
    name: "Астат",
    mass: 210,
    category: "halogen",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",
    meltingPoint: 302,
    boilingPoint: 337,
    density: 7,
    group: 17,
    period: 6,
  },
  {
    num: 86,
    symbol: "Rn",
    name: "Радон",
    mass: 222,
    category: "noble",
    electronConfig: "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",
    meltingPoint: -71,
    boilingPoint: -61.7,
    density: 0.00973,
    group: 18,
    period: 6,
  },
  {
    num: 87,
    symbol: "Fr",
    name: "Франций",
    mass: 223,
    category: "alkali",
    electronConfig: "[Rn] 7s¹",
    meltingPoint: 27,
    boilingPoint: 677,
    density: 1.87,
    group: 1,
    period: 7,
  },
  {
    num: 88,
    symbol: "Ra",
    name: "Радий",
    mass: 226,
    category: "alkaline",
    electronConfig: "[Rn] 7s²",
    meltingPoint: 696,
    boilingPoint: 1737,
    density: 5.5,
    group: 2,
    period: 7,
  },
  {
    num: 89,
    symbol: "Ac",
    name: "Актиний",
    mass: 227,
    category: "actinide",
    electronConfig: "[Rn] 6d¹ 7s²",
    meltingPoint: 1050,
    boilingPoint: 3198,
    density: 10.07,
    group: 3,
    period: 7,
  },
  {
    num: 90,
    symbol: "Th",
    name: "Торий",
    mass: 232.04,
    category: "actinide",
    electronConfig: "[Rn] 6d² 7s²",
    meltingPoint: 1750,
    boilingPoint: 4788,
    density: 11.72,
    group: null,
    period: 7,
  },
  {
    num: 91,
    symbol: "Pa",
    name: "Протактиний",
    mass: 231.04,
    category: "actinide",
    electronConfig: "[Rn] 5f² 6d¹ 7s²",
    meltingPoint: 1572,
    boilingPoint: 4000,
    density: 15.37,
    group: null,
    period: 7,
  },
  {
    num: 92,
    symbol: "U",
    name: "Уран",
    mass: 238.03,
    category: "actinide",
    electronConfig: "[Rn] 5f³ 6d¹ 7s²",
    meltingPoint: 1135,
    boilingPoint: 4131,
    density: 18.95,
    group: null,
    period: 7,
  },
  {
    num: 93,
    symbol: "Np",
    name: "Нептуний",
    mass: 237,
    category: "actinide",
    electronConfig: "[Rn] 5f⁴ 6d¹ 7s²",
    meltingPoint: 644,
    boilingPoint: 3902,
    density: 20.45,
    group: null,
    period: 7,
  },
  {
    num: 94,
    symbol: "Pu",
    name: "Плутоний",
    mass: 244,
    category: "actinide",
    electronConfig: "[Rn] 5f⁶ 7s²",
    meltingPoint: 640,
    boilingPoint: 3228,
    density: 19.84,
    group: null,
    period: 7,
  },
  {
    num: 95,
    symbol: "Am",
    name: "Америций",
    mass: 243,
    category: "actinide",
    electronConfig: "[Rn] 5f⁷ 7s²",
    meltingPoint: 1176,
    boilingPoint: 2011,
    density: 13.69,
    group: null,
    period: 7,
  },
  {
    num: 96,
    symbol: "Cm",
    name: "Кюрий",
    mass: 247,
    category: "actinide",
    electronConfig: "[Rn] 5f⁷ 6d¹ 7s²",
    meltingPoint: 1345,
    boilingPoint: 3110,
    density: 13.51,
    group: null,
    period: 7,
  },
  {
    num: 97,
    symbol: "Bk",
    name: "Берклий",
    mass: 247,
    category: "actinide",
    electronConfig: "[Rn] 5f⁹ 7s²",
    meltingPoint: 1050,
    boilingPoint: 2627,
    density: 14.79,
    group: null,
    period: 7,
  },
  {
    num: 98,
    symbol: "Cf",
    name: "Калифорний",
    mass: 251,
    category: "actinide",
    electronConfig: "[Rn] 5f¹⁰ 7s²",
    meltingPoint: 900,
    boilingPoint: 1470,
    density: 15.1,
    group: null,
    period: 7,
  },
  {
    num: 99,
    symbol: "Es",
    name: "Эйнштейний",
    mass: 252,
    category: "actinide",
    electronConfig: "[Rn] 5f¹¹ 7s²",
    meltingPoint: 860,
    boilingPoint: 1130,
    density: null,
    group: null,
    period: 7,
  },
  {
    num: 100,
    symbol: "Fm",
    name: "Фермий",
    mass: 257,
    category: "actinide",
    electronConfig: "[Rn] 5f¹² 7s²",
    meltingPoint: 1527,
    boilingPoint: null,
    density: null,
    group: null,
    period: 7,
  },
  {
    num: 101,
    symbol: "Md",
    name: "Менделевий",
    mass: 258,
    category: "actinide",
    electronConfig: "[Rn] 5f¹³ 7s²",
    meltingPoint: 827,
    boilingPoint: null,
    density: null,
    group: null,
    period: 7,
  },
  {
    num: 102,
    symbol: "No",
    name: "Нобелий",
    mass: 259,
    category: "actinide",
    electronConfig: "[Rn] 5f¹⁴ 7s²",
    meltingPoint: 827,
    boilingPoint: null,
    density: null,
    group: null,
    period: 7,
  },
  {
    num: 103,
    symbol: "Lr",
    name: "Лоуренсий",
    mass: 266,
    category: "actinide",
    electronConfig: "[Rn] 5f¹⁴ 6d¹ 7s²",
    meltingPoint: 1627,
    boilingPoint: null,
    density: null,
    group: 3,
    period: 7,
  },
  {
    num: 104,
    symbol: "Rf",
    name: "Резерфордий",
    mass: 267,
    category: "transition",
    electronConfig: "[Rn] 5f¹⁴ 6d² 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 4,
    period: 7,
  },
  {
    num: 105,
    symbol: "Db",
    name: "Дубний",
    mass: 268,
    category: "transition",
    electronConfig: "[Rn] 5f¹⁴ 6d³ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 5,
    period: 7,
  },
  {
    num: 106,
    symbol: "Sg",
    name: "Сиборгий",
    mass: 269,
    category: "transition",
    electronConfig: "[Rn] 5f¹⁴ 6d⁴ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 6,
    period: 7,
  },
  {
    num: 107,
    symbol: "Bh",
    name: "Борий",
    mass: 270,
    category: "transition",
    electronConfig: "[Rn] 5f¹⁴ 6d⁵ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 7,
    period: 7,
  },
  {
    num: 108,
    symbol: "Hs",
    name: "Хассий",
    mass: 277,
    category: "transition",
    electronConfig: "[Rn] 5f¹⁴ 6d⁶ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 8,
    period: 7,
  },
  {
    num: 109,
    symbol: "Mt",
    name: "Мейтнерий",
    mass: 278,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d⁷ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 9,
    period: 7,
  },
  {
    num: 110,
    symbol: "Ds",
    name: "Дармштадтий",
    mass: 281,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d⁸ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 10,
    period: 7,
  },
  {
    num: 111,
    symbol: "Rg",
    name: "Рентгений",
    mass: 282,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d⁹ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 11,
    period: 7,
  },
  {
    num: 112,
    symbol: "Cn",
    name: "Коперниций",
    mass: 285,
    category: "transition",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 12,
    period: 7,
  },
  {
    num: 113,
    symbol: "Nh",
    name: "Нихоний",
    mass: 286,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 13,
    period: 7,
  },
  {
    num: 114,
    symbol: "Fl",
    name: "Флеровий",
    mass: 289,
    category: "post-transition",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 14,
    period: 7,
  },
  {
    num: 115,
    symbol: "Mc",
    name: "Московий",
    mass: 290,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 15,
    period: 7,
  },
  {
    num: 116,
    symbol: "Lv",
    name: "Ливерморий",
    mass: 293,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 16,
    period: 7,
  },
  {
    num: 117,
    symbol: "Ts",
    name: "Теннессин",
    mass: 294,
    category: "unknown",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 17,
    period: 7,
  },
  {
    num: 118,
    symbol: "Og",
    name: "Оганессон",
    mass: 294,
    category: "noble",
    electronConfig: "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",
    meltingPoint: null,
    boilingPoint: null,
    density: null,
    group: 18,
    period: 7,
  },
]
