const molecules = [
  {
    id: "water",
    name: "Су (H₂O)",
    formula: "H₂O",
    description: "Жердегі өмірдің негізі. Екі сутегі мен бір оттегі атомынан тұрады.",
    atoms: [
      { element: "O", x: 0, y: 0, z: 0, color: "#ff0000", radius: 1.5 },
      { element: "H", x: -1.5, y: 1, z: 0, color: "#ffffff", radius: 1 },
      { element: "H", x: 1.5, y: 1, z: 0, color: "#ffffff", radius: 1 },
    ],
    bonds: [
      [0, 1],
      [0, 2],
    ],
    facts: "Суды 70-ке жуық химиялық реакцияда еріткіш ретінде қолданады.",
  },
  {
    id: "co2",
    name: "Көмірқышқыл газы (CO₂)",
    formula: "CO₂",
    description: "Фотосинтез үшін маңызды газ. Бір көміртегі мен екі оттегіден тұрады.",
    atoms: [
      { element: "C", x: 0, y: 0, z: 0, color: "#404040", radius: 1.4 },
      { element: "O", x: -2.2, y: 0, z: 0, color: "#ff0000", radius: 1.3 },
      { element: "O", x: 2.2, y: 0, z: 0, color: "#ff0000", radius: 1.3 },
    ],
    bonds: [
      [0, 1],
      [0, 2],
    ],
    facts: "Атмосферада 0.04% болса да, парниктік эффектіге үлкен әсер етеді.",
  },
  {
    id: "methane",
    name: "Метан (CH₄)",
    formula: "CH₄",
    description: "Ең қарапайым органикалық қосылыс. Табиғи газдың негізгі құрамы.",
    atoms: [
      { element: "C", x: 0, y: 0, z: 0, color: "#404040", radius: 1.4 },
      { element: "H", x: 1.5, y: 0, z: 0, color: "#ffffff", radius: 1 },
      { element: "H", x: -1.5, y: 0, z: 0, color: "#ffffff", radius: 1 },
      { element: "H", x: 0, y: 1.5, z: 0, color: "#ffffff", radius: 1 },
      { element: "H", x: 0, y: -1.5, z: 0, color: "#ffffff", radius: 1 },
    ],
    bonds: [
      [0, 1],
      [0, 2],
      [0, 3],
      [0, 4],
    ],
    facts: "Метан - тетраэдр пішінді молекула, барлық бұрыштары 109.5°.",
  },
  {
    id: "ammonia",
    name: "Аммиак (NH₃)",
    formula: "NH₃",
    description: "Өнеркәсіпте өте маңызды, тыңайтқыштар өндірісінде қолданылады.",
    atoms: [
      { element: "N", x: 0, y: 0, z: 0, color: "#0000ff", radius: 1.4 },
      { element: "H", x: 1.5, y: 1, z: 0, color: "#ffffff", radius: 1 },
      { element: "H", x: -1.5, y: 1, z: 0, color: "#ffffff", radius: 1 },
      { element: "H", x: 0, y: -1, z: 1.2, color: "#ffffff", radius: 1 },
    ],
    bonds: [
      [0, 1],
      [0, 2],
      [0, 3],
    ],
    facts: "Аммиак - пирамида пішінді молекула, өткір иісі бар.",
  },
  {
    id: "glucose",
    name: "Глюкоза (C₆H₁₂O₆)",
    formula: "C₆H₁₂O₆",
    description: "Жасушалардағы негізгі энергия көзі. Қанттың қарапайым түрі.",
    atoms: [
      { element: "C", x: 0, y: 0, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 2, y: 0, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 3, y: 1.5, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 2, y: 3, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 0, y: 3, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: -1, y: 1.5, z: 0, color: "#404040", radius: 1.3 },
      { element: "O", x: 1, y: -1.5, z: 0, color: "#ff0000", radius: 1.2 },
    ],
    bonds: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [5, 0],
      [1, 6],
    ],
    facts: "Глюкоза - сақина түріндегі молекула, тамақ арқылы алынатын негізгі энергия көзі.",
  },
  {
    id: "ethanol",
    name: "Этанол (C₂H₅OH)",
    formula: "C₂H₅OH",
    description: "Алкоголь ішімдіктердің негізгі құрамы.",
    atoms: [
      { element: "C", x: -1.5, y: 0, z: 0, color: "#404040", radius: 1.4 },
      { element: "C", x: 1.5, y: 0, z: 0, color: "#404040", radius: 1.4 },
      { element: "O", x: 3.5, y: 0, z: 0, color: "#ff0000", radius: 1.3 },
      { element: "H", x: -2.5, y: 1.2, z: 0, color: "#ffffff", radius: 0.9 },
      { element: "H", x: -2.5, y: -1.2, z: 0, color: "#ffffff", radius: 0.9 },
      { element: "H", x: 4.5, y: 0.8, z: 0, color: "#ffffff", radius: 0.9 },
    ],
    bonds: [
      [0, 1],
      [1, 2],
      [0, 3],
      [0, 4],
      [2, 5],
    ],
    facts: "Этанолды қант ашыту арқылы алады, дезинфекция үшін де қолданылады.",
  },
  {
    id: "nacl",
    name: "Тұз (NaCl)",
    formula: "NaCl",
    description: "Ас тұзы, натрий мен хлордан тұратын иондық қосылыс.",
    atoms: [
      { element: "Na", x: 0, y: 0, z: 0, color: "#8000ff", radius: 1.6 },
      { element: "Cl", x: 2.5, y: 0, z: 0, color: "#00ff00", radius: 1.5 },
    ],
    bonds: [[0, 1]],
    facts: "NaCl кристалды тор құрылымында болады, әрбір ион 6 көршімен қоршалған.",
  },
  {
    id: "benzene",
    name: "Бензол (C₆H₆)",
    formula: "C₆H₆",
    description: "Ароматты көмірсутек, көптеген органикалық синтездердің негізі.",
    atoms: [
      { element: "C", x: 0, y: 2, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 1.7, y: 1, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 1.7, y: -1, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: 0, y: -2, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: -1.7, y: -1, z: 0, color: "#404040", radius: 1.3 },
      { element: "C", x: -1.7, y: 1, z: 0, color: "#404040", radius: 1.3 },
    ],
    bonds: [
      [0, 1],
      [1, 2],
      [2, 3],
      [3, 4],
      [4, 5],
      [5, 0],
    ],
    facts: "Бензол - алты мүшелі сақина, электрондар резонанс арқылы делокализацияланған.",
  },
]
